### PR TITLE
Ensure that job names are unique enough to be easily identifiable

### PR DESCRIPTION
**Pull request by GLundh**
Should make the plugin usable with Multibranch Pipeline jobs.

### CODE REVIEW

**Comment by GLundh** [comment]
Idea by @jonsten .

@jonsten: This is the fastest way I could calculate decent project names with consistent results. Would be nice if you could take a look at it before I add the test cases.

**Comment by jaxzin** [comment]
@GLundh I'm grabbing the built PR here: https://ci.jenkins.io/job/Plugins/job/yet-another-build-visualizer-plugin/job/PR-5/1/artifact/target/yet-another-build-visualizer.hpi and testing it now

**Comment by jaxzin** [comment]
Looks great on my server 
image

**Comment by GLundh** [comment]
Great. Thanks for testing it!

I'll write some testcases and issue a new release sometime next week.

**Comment by GLundh** [comment]
Extracted name normalizing code to separate classes for testability. Ready for review.

**Comment by GLundh** [comment]
Fixed your review comments + some algorithmic optimizations to minimize the amount of parental traversing.

I'm much more happy with this change. Please take a look.

**Pull request merged**
